title: VibeDoc - AI驱动的开发计划生成器
emoji: 🚀
colorFrom: blue
colorTo: purple
sdk: docker
app_port: 3000
pinned: true
license: mit
tags:
  - AI
  - MCP Server
  - Development Planning
  - Next.js
  - TypeScript
  - Silicon Flow
short_description: 基于AI的智能开发计划生成工具，参赛魔搭AI Hackathon 2025 MCP Server开发赛道

# 环境变量配置
suggested_space_vars:
  - name: SILICONFLOW_API_KEY
    description: Silicon Flow API密钥
    default: ""
    required: true
  - name: NODE_ENV
    description: 运行环境
    default: "production"
    required: false

# 部署配置
models: []
datasets: []
spaces: []

# 硬件要求
hardware:
  cpu: "2"
  memory: "4Gi"
  gpu: false
