export const SOP_TEMPLATE = [
  {
    step: 1,
    title: "确定要做什么",
    fields: [
      {
        id: "painPoints",
        label: "自己的痛点/痒点",
        type: "textarea",
        required: true,
        placeholder: "描述你遇到的具体问题或需要解决的痛点...",
      },
      {
        id: "newTerms",
        label: "新词/热词",
        type: "text",
        required: true,
        placeholder: "相关的新兴概念、技术词汇或热门话题...",
      },
      {
        id: "successCases",
        label: "致敬成功案例",
        type: "textarea",
        required: true,
        placeholder: "参考的成功产品或案例，说明为什么值得学习...",
      },
    ],
  },
  {
    step: 2,
    title: "确定产品名称",
    fields: [
      {
        id: "productName",
        label: "产品名称",
        type: "text",
        required: true,
        placeholder: "输入你的产品名称...",
        recommendations: ["GPT生成", "品牌词典", "同义词工具"],
      },
      {
        id: "domainName",
        label: "域名",
        type: "text",
        required: true,
        placeholder: "输入域名（如：example.com）...",
        recommendations: ["namecheap", "GoDaddy", "域名查询工具"],
      },
      {
        id: "brandingConcept",
        label: "品牌概念",
        type: "textarea",
        required: true,
        placeholder: "描述产品的品牌定位和核心概念...",
        recommendations: ["品牌策略工具", "竞品分析", "用户调研"],
      },
    ],
  },
  {
    step: 3,
    title: "把产品做出来",
    fields: [
      {
        id: "techStack",
        label: "技术栈选择",
        type: "textarea",
        required: true,
        placeholder: "选择合适的技术栈和开发工具...",
        recommendations: ["Next.js", "React", "Vue.js", "Node.js", "Python"],
      },
      {
        id: "deployment",
        label: "部署方案",
        type: "text",
        required: true,
        placeholder: "选择部署平台和方案...",
        recommendations: ["Vercel", "Netlify", "AWS", "Railway", "Docker"],
      },
      {
        id: "developmentPlan",
        label: "开发计划",
        type: "textarea",
        required: true,
        placeholder: "制定详细的开发计划和时间安排...",
        recommendations: ["敏捷开发", "MVP方法", "项目管理工具"],
      },
      {
        id: "designSystem",
        label: "设计系统",
        type: "text",
        required: true,
        placeholder: "选择UI/UX设计方案...",
        recommendations: ["Tailwind CSS", "Shadcn/UI", "Material UI", "Figma"],
      },
    ],
  },
  {
    step: 4,
    title: "部署上线",
    fields: [
      {
        id: "hostingPlatform",
        label: "托管平台",
        type: "text",
        required: true,
        placeholder: "选择托管和部署平台...",
        recommendations: ["Vercel", "Netlify", "AWS", "Railway", "DigitalOcean"],
      },
      {
        id: "domainSetup",
        label: "域名配置",
        type: "text",
        required: true,
        placeholder: "配置自定义域名和DNS设置...",
        recommendations: ["Cloudflare", "Route 53", "DNSPod", "域名解析"],
      },
      {
        id: "sslCertificate",
        label: "SSL证书",
        type: "text",
        required: true,
        placeholder: "配置HTTPS和SSL证书...",
        recommendations: ["Let's Encrypt", "Cloudflare SSL", "自动SSL"],
      },
      {
        id: "performanceOptimization",
        label: "性能优化",
        type: "textarea",
        required: true,
        placeholder: "优化网站性能和加载速度...",
        recommendations: ["CDN配置", "图片优化", "缓存策略", "压缩工具"],
      },
    ],
  },
  {
    step: 5,
    title: "推广宣传",
    fields: [
      {
        id: "socialMediaStrategy",
        label: "社交媒体策略",
        type: "textarea",
        required: true,
        placeholder: "制定社交媒体推广计划...",
        recommendations: ["Twitter", "LinkedIn", "微博", "小红书", "抖音"],
      },
      {
        id: "productLaunch",
        label: "产品发布",
        type: "textarea",
        required: true,
        placeholder: "选择产品发布平台和策略...",
        recommendations: ["ProductHunt", "HackerNews", "Reddit", "V2EX", "少数派"],
      },
      {
        id: "contentMarketing",
        label: "内容营销",
        type: "textarea",
        required: true,
        placeholder: "创建内容营销计划...",
        recommendations: ["博客文章", "视频教程", "案例分析", "技术分享"],
      },
      {
        id: "communityBuilding",
        label: "社区建设",
        type: "textarea",
        required: true,
        placeholder: "建立用户社区和反馈渠道...",
        recommendations: ["Discord", "Slack", "微信群", "QQ群", "Telegram"],
      },
    ],
  },
  {
    step: 6,
    title: "数据分析",
    fields: [
      {
        id: "analyticsSetup",
        label: "分析工具配置",
        type: "text",
        required: true,
        placeholder: "配置网站分析和数据追踪工具...",
        recommendations: ["Google Analytics", "Mixpanel", "Hotjar", "百度统计", "友盟"],
      },
      {
        id: "kpiDefinition",
        label: "关键指标定义",
        type: "textarea",
        required: true,
        placeholder: "定义产品的关键性能指标(KPI)...",
        recommendations: ["用户增长", "留存率", "转化率", "DAU/MAU", "收入指标"],
      },
      {
        id: "userBehaviorAnalysis",
        label: "用户行为分析",
        type: "textarea",
        required: true,
        placeholder: "分析用户使用行为和路径...",
        recommendations: ["漏斗分析", "热力图", "用户路径", "A/B测试", "用户反馈"],
      },
      {
        id: "performanceMetrics",
        label: "性能指标监控",
        type: "textarea",
        required: true,
        placeholder: "监控产品性能和技术指标...",
        recommendations: ["页面加载速度", "错误率", "可用性", "服务器监控", "CDN性能"],
      },
    ],
  },
  {
    step: 7,
    title: "运营迭代",
    fields: [
      {
        id: "userFeedback",
        label: "用户反馈收集",
        type: "textarea",
        required: true,
        placeholder: "建立用户反馈收集和处理机制...",
        recommendations: ["问卷调查", "用户访谈", "客服系统", "社区反馈", "应用商店评价"],
      },
      {
        id: "productIteration",
        label: "产品迭代计划",
        type: "textarea",
        required: true,
        placeholder: "制定产品功能迭代和优化计划...",
        recommendations: ["敏捷开发", "版本规划", "功能优先级", "用户故事", "开发周期"],
      },
      {
        id: "marketingOptimization",
        label: "营销优化",
        type: "textarea",
        required: true,
        placeholder: "优化营销策略和推广效果...",
        recommendations: ["内容优化", "SEO优化", "广告投放", "社交媒体", "合作伙伴"],
      },
      {
        id: "businessModel",
        label: "商业模式优化",
        type: "textarea",
        required: true,
        placeholder: "优化产品的商业模式和盈利方式...",
        recommendations: ["订阅模式", "广告收入", "付费功能", "企业服务", "数据服务"],
      },
    ],
  },
];